---

# Deploy Quay container registry as a quadlet service stack

- name: "Ensure prerequisites"
  ansible.builtin.include_tasks: "prerequisites.yml"

- name: "Generate Quay and Clair configuration files"
  ansible.builtin.include_tasks: "generate_configs.yml"

- name: "Deploy quadlet unit files"
  ansible.builtin.include_tasks: "deploy_quadlet_files.yml"

- name: "Initialize databases"
  ansible.builtin.include_tasks: "initialize_database.yml"

- name: "Start Quay services"
  ansible.builtin.include_tasks: "start_services.yml"

- name: "Validate the deployment"
  ansible.builtin.include_tasks: "validate_deployment.yml"
